### ISSUE TITLE
Classes and Methods

### ISSUE THREAD

**Issue by bren3582** [luoalex222/Luo_CSCI2270_FinalProject#1]
# Deck
- constructor to build deck
- shuffle
- pop
- number of cards
# Card
- constructor that takes a suit and value
- suit name
- card value
# Hand
- get cards
# Dealer
- hit
- stay
- double down
- split
# Bank
- player funds

**Comment by Alex-Luo** [comment]
Add split hand to hand class.

**Comment by bren3582** [comment]
All done except for Bank and Dealer's split function

**Comment by bren3582** [comment]
Decided not to add split function for now, closing
